# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/mysql2sqlite
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Lint and Build using Makefile

# Run builds for Pull Requests (new, updated)
# `synchronized` seems to equate to pushing new commits to a linked branch
# (whether force-pushed or not)
on:
  #push:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_code_with_makefile:
    name: Lint codebase using Makefile
    runs-on: ubuntu-latest
    # Default: 360 minutes
    timeout-minutes: 10
    container:
      # Use (lightly touched) mirror of current "vanilla" upstream golang image
      image: "ghcr.io/atc0005/go-ci:go-ci-stable-mirror-build"

    steps:
      - name: Print go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      # bsdmainutils provides "column" which is used by the Makefile
      - name: Install Ubuntu packages
        run: apt-get update && apt-get install -y --no-install-recommends make gcc bsdmainutils

      - name: Install Go linting tools
        run: make lintinstall

      # NOTE: We are intentionally *not* removing the repo-provided config
      # file (per GH-281) as this workflow is intended to emulate running the
      # Makefile via a local dev environment.
      #
      # - name: Remove repo-provided golangci-lint config file
      #   run: |
      #     # Remove the copy of the config file bundled with the repo/code so
      #     # that the configuration provided by the atc0005/go-ci project is
      #     # used instead
      #     rm -vf .golangci.yml

      - name: Run Go linting tools using project Makefile
        run: make linting

  # This is run from *within* a container that is itself within the GitHub
  # Actions environment. All of these commands are run within our container.
  build_dynamic_binaries_with_makefile:
    name: Build dynamically linked binaries using Makefile
    runs-on: ubuntu-latest
    # Default: 360 minutes
    timeout-minutes: 20
    container:
      # Use (lightly touched) mirror of current "vanilla" upstream golang image
      image: "ghcr.io/atc0005/go-ci:go-ci-stable-mirror-build"

    steps:
      - name: Print go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      # bsdmainutils provides "column" which is used by the Makefile
      # other packages are needed for cross-compilation
      - name: Install Ubuntu packages needed for cross-compilation
        run: |
          apt-get update && \
            apt-get install -y --no-install-recommends \
            make \
            bsdmainutils \
            gcc \
            gcc-multilib \
            gcc-mingw-w64

      - name: Build using project Makefile
        run: make all

  # This is run from *within* a container that is itself within the GitHub
  # Actions environment. All of these commands are run within our container.
  build_static_binaries_with_makefile:
    name: Build statically linked binaries using Makefile
    runs-on: ubuntu-latest
    # Default: 360 minutes
    timeout-minutes: 20
    container:
      # Use (lightly touched) mirror of current "vanilla" upstream golang image
      image: "ghcr.io/atc0005/go-ci:go-ci-stable-mirror-build"

    steps:
      - name: Print go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      # bsdmainutils provides "column" which is used by the Makefile
      # other packages are needed for cross-compilation
      - name: Install Ubuntu packages needed for cross-compilation
        run: |
          apt-get update && \
            apt-get install -y --no-install-recommends \
            make \
            bsdmainutils \
            gcc \
            gcc-multilib \
            gcc-mingw-w64

      - name: Build using project Makefile
        run: make all-static

  # This is run directly within the GitHub Actions environment and calls the
  # `docker` command to perform specific build tasks within Docker containers.
  # Prep steps are run within the GitHub Actions environment and not within
  # the containers.
  build_static_binaries_with_makefile_docker_recipe:
    name: Build static binaries using Docker images
    runs-on: ubuntu-latest
    # Default: 360 minutes
    timeout-minutes: 20

    steps:
      # This doesn't apply here; were we to execute this, it would show us the
      # Go version provided by the GitHub Actions environment (VM) and not our
      # Docker images.
      #
      # - name: Print go version
      #   run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      # bsdmainutils provides "column" which is used by the Makefile
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends \
            bsdmainutils \
            make

      - name: Build using project Makefile Docker recipe
        run: make docker
